theme = "unicorn"

baseurl = "https://unicornfantasia.netlify.app/"
title = "ğŸ¦„UnicornFantasia"

[params.utterances]
# https://utteranc.es/
repo = "owner/repo"
issueTerm = "pathname"
theme = "github-light"

[params]
description = "æ°—ã«ãªã£ãŸæŠ€è¡“ãªã©ã‚’ä¸­å¿ƒã«æ›¸ã„ã¦ã„ã“ã†ã¨ãŠã‚‚ã„ã¾ã™!"

[params.author]
github = "ress997"
twitter = "ress997"

[params.images]
icon = "https://twemoji.maxcdn.com/v/13.1.0/svg/1f98b.svg"

[[menus.main]]
url = "/about/"
name = "About"

[[menus.main]]
url = "/tags/"
name = "Tag"

[outputs]
page = ["HTML", "AMP"]

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[taxonomies]
tag = "tags"
